-- R29: kits can be changed per quotation (items taken out, optional items added) and transport for the
-- school's location is added per quotation, hidden inside the price.
ALTER TABLE "QuotationItem" ADD COLUMN "kit" JSONB,
ADD COLUMN "transport" DECIMAL(12,2) NOT NULL DEFAULT 0;

-- Prices come only from the client's Excel price list; the class-kit prices taken from the sample PO are
-- cleared (only where they are still the PO's figures, so a price the team typed is kept).
UPDATE "Product" SET "price" = NULL WHERE ("code", "price") IN (('K01', 2360), ('K02', 2760), ('K03', 2975), ('K04', 3175));

-- Nursery kit types: each item's price is stored with the contents, and the fixed "Freight Transport"
-- (100 / MRP 0) leaves the Focus and Plus kits (transport now depends on location): 2,954 → 2,854 and
-- 3,244 → 3,144, unless the price was already changed by hand.
UPDATE "Product" SET "contents" = '[{"title":"Core Kit","items":["Book 1 to 9","Portfolio Book","Portfolio File","Report Card","Assessments"],"prices":[{"sp":1792,"mrp":2688},{"sp":130,"mrp":300},{"sp":25,"mrp":45},{"sp":65,"mrp":90},{"sp":100,"mrp":125}]}]'::jsonb, "price" = CASE WHEN "price" = 2112 THEN 2112 ELSE "price" END WHERE "code" = 'K05' AND "name" = 'Nursery Core Kit';
UPDATE "Product" SET "contents" = '[{"title":"Class Connect","items":["Book 1 to 9"],"prices":[{"sp":1792,"mrp":2688}]},{"title":"Home Connect","items":["Flash Cards","10 Academic Posters","3 Tracing Sheets","Marker","Portfolio Book","Portfolio File"],"prices":[{"sp":40,"mrp":75},{"sp":50,"mrp":100},{"sp":70,"mrp":80},{"sp":7,"mrp":12},{"sp":130,"mrp":300},{"sp":25,"mrp":45}]},{"title":"Skill Booster","items":["Shape Kit","20 Art & Craft activities (Take Aways)"],"prices":[{"sp":20,"mrp":35},{"sp":220,"mrp":430}]},{"title":"Essential Kit","items":["I-card - Student","Escort Card 2","3 Greetings with Envelopes","Sports Certificate","Graduation Certificate","Report Card","Kit Box & Packaging","Assessments","Kit Box"],"prices":[{"sp":60,"mrp":70},{"sp":10,"mrp":15},{"sp":45,"mrp":60},{"sp":15,"mrp":25},{"sp":15,"mrp":25},{"sp":65,"mrp":90},{"sp":120,"mrp":145},{"sp":100,"mrp":125},{"sp":70,"mrp":110}]}]'::jsonb, "price" = CASE WHEN "price" = 2954 THEN 2854 ELSE "price" END WHERE "code" = 'K06' AND "name" = 'Nursery Focus Kit';
UPDATE "Product" SET "contents" = '[{"title":"Class Connect","items":["Book 1 to 9","Practice Notebook - Letters Nursery","Practice Notebook - Numbers Nursery"],"prices":[{"sp":1792,"mrp":2688},{"sp":55,"mrp":90},{"sp":55,"mrp":90}]},{"title":"Home Connect","items":["Flash Cards","10 Academic Posters","3 Tracing Sheets","Marker","Portfolio Book","Portfolio File"],"prices":[{"sp":40,"mrp":75},{"sp":50,"mrp":100},{"sp":70,"mrp":80},{"sp":7,"mrp":12},{"sp":130,"mrp":300},{"sp":25,"mrp":45}]},{"title":"Skill Booster","items":["Shape Kit","20 Art & Craft activities (Take Aways)"],"prices":[{"sp":20,"mrp":35},{"sp":220,"mrp":430}]},{"title":"Essential Kit","items":["I-card - Student","Escort Card 2","3 Greetings with Envelopes","Sports Certificate","Graduation Certificate","Report Card","Diary","Memory album","Sports Medal","Kit Box & Packaging","Assessments","Kit Box"],"prices":[{"sp":60,"mrp":70},{"sp":10,"mrp":15},{"sp":45,"mrp":60},{"sp":15,"mrp":25},{"sp":15,"mrp":25},{"sp":65,"mrp":90},{"sp":60,"mrp":120},{"sp":90,"mrp":200},{"sp":30,"mrp":40},{"sp":120,"mrp":145},{"sp":100,"mrp":125},{"sp":70,"mrp":110}]}]'::jsonb, "price" = CASE WHEN "price" = 3244 THEN 3144 ELSE "price" END WHERE "code" = 'K07' AND "name" = 'Nursery Plus Kit';
