-- Kit contents and checklist colour on products; our PO number and PO template details on quotations.
ALTER TABLE "Product" ADD COLUMN "color" TEXT,
ADD COLUMN "contents" JSONB;
ALTER TABLE "Quotation" ADD COLUMN "poDetails" JSONB,
ADD COLUMN "poNumber" TEXT;
CREATE UNIQUE INDEX "Quotation_poNumber_key" ON "Quotation"("poNumber");

-- One-time catalogue change requested by the owner (R27): remove the 7 sample services (P01–P07, only where the name is still the sample's)
-- the same way "Delete product" does (documents keep their text, links are dropped), then add
-- Wonder Learning's class kits and optional add-ons (src/lib/kits.ts). Existing codes are left alone.
DELETE FROM "LeadInterest" WHERE "productId" IN (SELECT "id" FROM "Product" WHERE ("code" = 'P01' AND "name" = 'Curriculum License') OR ("code" = 'P02' AND "name" = 'Preschool Setup Package') OR ("code" = 'P03' AND "name" = 'Teacher Training') OR ("code" = 'P04' AND "name" = 'Parent Workshop') OR ("code" = 'P05' AND "name" = 'School Audit') OR ("code" = 'P06' AND "name" = 'Marketing Campaign') OR ("code" = 'P07' AND "name" = 'Branding Support'));
DELETE FROM "OpportunityItem" WHERE "productId" IN (SELECT "id" FROM "Product" WHERE ("code" = 'P01' AND "name" = 'Curriculum License') OR ("code" = 'P02' AND "name" = 'Preschool Setup Package') OR ("code" = 'P03' AND "name" = 'Teacher Training') OR ("code" = 'P04' AND "name" = 'Parent Workshop') OR ("code" = 'P05' AND "name" = 'School Audit') OR ("code" = 'P06' AND "name" = 'Marketing Campaign') OR ("code" = 'P07' AND "name" = 'Branding Support'));
UPDATE "QuotationItem" SET "productId" = NULL WHERE "productId" IN (SELECT "id" FROM "Product" WHERE ("code" = 'P01' AND "name" = 'Curriculum License') OR ("code" = 'P02' AND "name" = 'Preschool Setup Package') OR ("code" = 'P03' AND "name" = 'Teacher Training') OR ("code" = 'P04' AND "name" = 'Parent Workshop') OR ("code" = 'P05' AND "name" = 'School Audit') OR ("code" = 'P06' AND "name" = 'Marketing Campaign') OR ("code" = 'P07' AND "name" = 'Branding Support'));
UPDATE "SalesOrderItem" SET "productId" = NULL WHERE "productId" IN (SELECT "id" FROM "Product" WHERE ("code" = 'P01' AND "name" = 'Curriculum License') OR ("code" = 'P02' AND "name" = 'Preschool Setup Package') OR ("code" = 'P03' AND "name" = 'Teacher Training') OR ("code" = 'P04' AND "name" = 'Parent Workshop') OR ("code" = 'P05' AND "name" = 'School Audit') OR ("code" = 'P06' AND "name" = 'Marketing Campaign') OR ("code" = 'P07' AND "name" = 'Branding Support'));
UPDATE "InvoiceItem" SET "productId" = NULL WHERE "productId" IN (SELECT "id" FROM "Product" WHERE ("code" = 'P01' AND "name" = 'Curriculum License') OR ("code" = 'P02' AND "name" = 'Preschool Setup Package') OR ("code" = 'P03' AND "name" = 'Teacher Training') OR ("code" = 'P04' AND "name" = 'Parent Workshop') OR ("code" = 'P05' AND "name" = 'School Audit') OR ("code" = 'P06' AND "name" = 'Marketing Campaign') OR ("code" = 'P07' AND "name" = 'Branding Support'));
DELETE FROM "Product" WHERE ("code" = 'P01' AND "name" = 'Curriculum License') OR ("code" = 'P02' AND "name" = 'Preschool Setup Package') OR ("code" = 'P03' AND "name" = 'Teacher Training') OR ("code" = 'P04' AND "name" = 'Parent Workshop') OR ("code" = 'P05' AND "name" = 'School Audit') OR ("code" = 'P06' AND "name" = 'Marketing Campaign') OR ("code" = 'P07' AND "name" = 'Branding Support');

INSERT INTO "Product" ("id", "code", "name", "type", "category", "price", "gstRate", "active", "sortOrder", "contents", "color", "updatedAt") VALUES
  ('cat_k01', 'K01', 'Play Group Kit', 'MATERIAL', 'Student kit', 2360, 0, true, 1, '[{"title":"Common Kit | 19 objects","items":["School Bag","Student''s Diary","Child I Card with holder & sling","Parent - Escort Card","Birthday Greeting Card","Children’s Day Greeting Card","New Year Greeting Card","Grand Parents Day Invitation card","PTM Invitation Card – 1","PTM Invitation Card – 2","PTM Invitation Card – 3","PTM Invitation Card – 4","Sports Day Invitation card","Sports Day Medal","Sports Day Certificate","Annual Day Invitation card","Report Card / Achievement Card","Graduation Certificate","My Book of Memories"]},{"title":"Academic Kit | 6 Text Books","items":["TB - My A to Z Picture Text Book","TB - My 1 to 10 Number Text Book","TB – My book of Concepts","TB - My Scribbling book","TB – Book of Festivals","TB - Rhymes - Introductory"]},{"title":"Resource Kit – School | 3 objects","items":["Portfolio File","Portfolio Book","Art & Craft Kit"]},{"title":"Resource Kit – Home | 6 objects","items":["Flash Cards","Academic Posters","Conical Crayon Box","Plastic Scissor","Apron","Play Dough kit"]}]'::jsonb, '#F08A1C', CURRENT_TIMESTAMP),
  ('cat_k02', 'K02', 'Nursery Kit', 'MATERIAL', 'Student kit', 2760, 0, true, 2, '[{"title":"Common Kit | 19 objects","items":["School Bag","Student''s Diary","Child I Card with holder & sling","Parent - Escort Card","Birthday Greeting Card","Children’s Day Greeting Card","New Year Greeting Card","Grand Parents Day Invitation card","PTM Invitation Card – 1","PTM Invitation Card – 2","PTM Invitation Card – 3","PTM Invitation Card – 4","Sports Day Invitation card","Sports Day Medal","Sports Day Certificate","Annual Day Invitation card","Report Card / Achievement Card","Graduation Certificate","My Book of Memories"]},{"title":"Academic Kit | 10 Text Books","items":["Text Book- 1","Text Book- 2","Text Book- 3","Text Book- 4","Text Book- 5","Text Book- 6","Text Book- 7","Text Book- 8","Text Book- 9","Text Book- 10"]},{"title":"Optional Notebooks","items":["My Practice Notebook – Maths","My Practice Notebook – English"]},{"title":"Resource Kit – School | 3 objects","items":["Portfolio File","Portfolio Book","Art & Craft Kit"]},{"title":"Resource Kit – Home | 5 objects","items":["Flash Cards","Academic Posters","Tracing Sheets","Writing Marker / Sketch pen","Crayon Box"]}]'::jsonb, '#EE2A50', CURRENT_TIMESTAMP),
  ('cat_k03', 'K03', 'LKG / Jr. KG Kit', 'MATERIAL', 'Student kit', 2975, 0, true, 3, '[{"title":"Common Kit | 19 objects","items":["School Bag","Student''s Diary","Child I Card with holder & sling","Parent - Escort Card","Birthday Greeting Card","Children’s Day Greeting Card","New Year Greeting Card","Grand Parents Day Invitation card","PTM Invitation Card – 1","PTM Invitation Card – 2","PTM Invitation Card – 3","PTM Invitation Card – 4","Sports Day Invitation card","Sports Day Medal","Sports Day Certificate","Annual Day Invitation card","Report Card / Achievement Card","Graduation Certificate","My Book of Memories"]},{"title":"Academic Kit | 10 Text Books + 4 Notebooks","items":["Text Book- 1","Text Book- 2","Text Book- 3","Text Book- 4","Text Book- 5","Text Book- 6","Text Book- 7","Text Book- 8","Text Book- 9","Text Book- 10","NB – My English Writing Book- 1","NB – My English Writing Book- 2","NB - My Number Writing Book- 1","NB - My Number Writing Book- 2"]},{"title":"Optional Subjects","items":["Hindi Akshar Gyan – Swar Text Book","Hindi Akshar Gyan – Vyanjan Text Book","My 5 Line Note Book – Swar","My 5 Line Note Book – Vyanjan"]},{"title":"Resource Kit – School | 3 objects","items":["Portfolio File","Portfolio Book","Art & Craft Kit"]},{"title":"Resource Kit – Home | 5 objects","items":["Flash Cards","Academic Posters","Tracing Sheets","Writing Marker / Sketch pen","Crayon Box"]}]'::jsonb, '#3CAE1A', CURRENT_TIMESTAMP),
  ('cat_k04', 'K04', 'UKG / Sr. KG Kit', 'MATERIAL', 'Student kit', 3175, 0, true, 4, '[{"title":"Common Kit | 19 objects","items":["School Bag","Student''s Diary","Child I Card with holder & sling","Parent - Escort Card","Birthday Greeting Card","Children’s Day Greeting Card","New Year Greeting Card","Grand Parents Day Invitation card","PTM Invitation Card – 1","PTM Invitation Card – 2","PTM Invitation Card – 3","PTM Invitation Card – 4","Sports Day Invitation card","Sports Day Medal","Sports Day Certificate","Annual Day Invitation card","Report Card / Achievement Card","Graduation Certificate","My Book of Memories"]},{"title":"Academic Kit | 10 Text Books + 5 Notebooks","items":["Text Book- 1","Text Book- 2","Text Book- 3","Text Book- 4","Text Book- 5","Text Book- 6","Text Book- 7","Text Book- 8","Text Book- 9","Text Book- 10","NB - My Notation Writing Notebook","NB - My Number Writing Notebook- 1","NB - My Number Writing Notebook- 2","NB – My Phonics Notebook- 1","NB – My Phonics Notebook- 2"]},{"title":"Optional Subjects","items":["My Cursive Textbook","My Phonics Reader Book","Hindi Text Book – Shabad Gyan","Hindi Text Book – Matra Gyan","NB - My 5 Line Notebook 1","NB - My 5 Line Notebook 2"]},{"title":"Resource Kit – School | 3 objects","items":["Portfolio File","Portfolio Book","Art & Craft Kit"]},{"title":"Resource Kit – Home | 5 objects","items":["Flash Cards","Academic Posters","Tracing Sheets","Writing Marker / Sketch pen","Jumbo Crayon Box"]}]'::jsonb, '#1C75BC', CURRENT_TIMESTAMP),
  ('cat_a01', 'A01', 'Hindi Swar TB & NB', 'MATERIAL', 'Optional add-on', NULL, 0, true, 5, NULL, NULL, CURRENT_TIMESTAMP),
  ('cat_a02', 'A02', 'Hindi Vyanjan TB & NB', 'MATERIAL', 'Optional add-on', NULL, 0, true, 6, NULL, NULL, CURRENT_TIMESTAMP),
  ('cat_a03', 'A03', 'Hindi Shabad Gyan TB & NB', 'MATERIAL', 'Optional add-on', NULL, 0, true, 7, NULL, NULL, CURRENT_TIMESTAMP),
  ('cat_a04', 'A04', 'Hindi Matra Gyan TB & NB', 'MATERIAL', 'Optional add-on', NULL, 0, true, 8, NULL, NULL, CURRENT_TIMESTAMP),
  ('cat_a05', 'A05', 'Cursive Text Book', 'MATERIAL', 'Optional add-on', NULL, 0, true, 9, NULL, NULL, CURRENT_TIMESTAMP),
  ('cat_a06', 'A06', 'My Reader Book- Phonics', 'MATERIAL', 'Optional add-on', NULL, 0, true, 10, NULL, NULL, CURRENT_TIMESTAMP),
  ('cat_a07', 'A07', 'Nursery Practice Notebooks- 2', 'MATERIAL', 'Optional add-on', NULL, 0, true, 11, NULL, NULL, CURRENT_TIMESTAMP)
ON CONFLICT ("code") DO NOTHING;
